# Generated by Django 4.2.16 on 2026-06-13 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                ("month", models.IntegerField(verbose_name="월")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "준비중"),
                            ("priority", "우선접수중"),
                            ("general", "일반접수중"),
                            ("closed", "마감"),
                            ("done", "종료"),
                        ],
                        default="preparing",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="정원")),
                (
                    "priority_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="우선접수 시작"
                    ),
                ),
                (
                    "priority_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="우선접수 종료"
                    ),
                ),
                (
                    "general_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="일반접수 시작"
                    ),
                ),
                (
                    "general_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="일반접수 종료"
                    ),
                ),
                ("notice", models.TextField(blank=True, verbose_name="공지 메시지")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gx_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_periods",
                        to="classes.gxclass",
                        verbose_name="수업",
                    ),
                ),
            ],
            options={
                "verbose_name": "등록 기간",
                "verbose_name_plural": "등록 기간 목록",
                "ordering": ["-year", "-month", "gx_class"],
                "unique_together": {("gx_class", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="PriorityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=100, verbose_name="메모"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_members",
                        to="enrollments.enrollmentperiod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "우선접수 대상자",
                "verbose_name_plural": "우선접수 대상자 목록",
                "unique_together": {("period", "user")},
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("phone", models.CharField(max_length=15, verbose_name="연락처")),
                ("building", models.CharField(max_length=10, verbose_name="동")),
                ("unit", models.CharField(max_length=10, verbose_name="호수")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "등록확정"),
                            ("waiting", "대기중"),
                            ("cancelled", "취소"),
                        ],
                        default="confirmed",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "enroll_type",
                    models.CharField(
                        choices=[
                            ("priority", "우선접수"),
                            ("general", "일반접수"),
                            ("manual", "수동등록"),
                        ],
                        default="general",
                        max_length=10,
                        verbose_name="접수유형",
                    ),
                ),
                (
                    "waiting_order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="대기순번"
                    ),
                ),
                (
                    "cancel_requested",
                    models.BooleanField(default=False, verbose_name="변경요청"),
                ),
                (
                    "cancel_message",
                    models.TextField(blank=True, verbose_name="변경요청내용"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="enrollments.enrollmentperiod",
                        verbose_name="등록기간",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "수강 등록",
                "verbose_name_plural": "수강 등록 목록",
                "ordering": ["period", "created_at"],
                "unique_together": {("period", "phone")},
            },
        ),
    ]
