# Generated by Django 4.2.16 on 2026-06-13 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complexes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "슈퍼관리자"),
                            ("complex_admin", "단지관리자"),
                            ("registered", "등록회원"),
                            ("unregistered", "미등록회원"),
                        ],
                        default="unregistered",
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, verbose_name="연락처"),
                ),
                (
                    "building",
                    models.CharField(blank=True, max_length=10, verbose_name="동"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=10, verbose_name="호수"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="승인여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "complex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="complexes.complex",
                        verbose_name="단지",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "회원 프로필",
                "verbose_name_plural": "회원 프로필 목록",
            },
        ),
    ]
