# Generated by Django 4.2.16 on 2026-06-13 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="보내는 분"
                    ),
                ),
                (
                    "sender_phone",
                    models.CharField(blank=True, max_length=15, verbose_name="연락처"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("guest", "비회원"),
                            ("member", "회원"),
                            ("registered", "등록회원"),
                        ],
                        default="guest",
                        max_length=15,
                        verbose_name="유형",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("is_read", models.BooleanField(default=False, verbose_name="읽음")),
                ("reply", models.TextField(blank=True, verbose_name="답변")),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="답변일시"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gx_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classes.gxclass",
                        verbose_name="관련수업",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "쪽지",
                "verbose_name_plural": "쪽지 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
