# Generated by Django 4.2.16 on 2026-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="단지명")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="단지코드"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="주소"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="운영중")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "단지",
                "verbose_name_plural": "단지 목록",
                "ordering": ["name"],
            },
        ),
    ]
