# Generated by Django 4.2.16 on 2026-06-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GxClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="수업명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "days",
                    models.CharField(
                        choices=[
                            ("MON", "월요일"),
                            ("THU", "목요일"),
                            ("MON_THU", "월/목"),
                        ],
                        max_length=10,
                        verbose_name="수업 요일",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="시작 시간")),
                ("end_time", models.TimeField(verbose_name="종료 시간")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=10, verbose_name="정원"),
                ),
                ("monthly_fee", models.PositiveIntegerField(verbose_name="월 수강료")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="운영 중"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "수업",
                "verbose_name_plural": "수업 목록",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="수업 날짜")),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="휴강"),
                ),
                (
                    "substitute_instructor",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="대강 강사"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="메모")),
                (
                    "gx_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="classes.gxclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "수업 회차",
                "verbose_name_plural": "수업 회차 목록",
                "ordering": ["-date"],
                "unique_together": {("gx_class", "date")},
            },
        ),
    ]
