# Generated by Django 4.2.16 on 2026-06-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("complexes", "0001_initial"),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gxclass",
            name="complex",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="complexes.complex",
                verbose_name="단지",
            ),
        ),
    ]
