# Generated by Django 4.2.16 on 2026-06-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_gxclass_complex"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "repeat_type",
                    models.CharField(
                        choices=[
                            ("weekly_1", "주 1회"),
                            ("weekly_2", "주 2회"),
                            ("weekly_3", "주 3회"),
                            ("custom", "직접 입력"),
                        ],
                        default="weekly_1",
                        max_length=10,
                        verbose_name="반복유형",
                    ),
                ),
                (
                    "day_1",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                            (6, "일요일"),
                        ],
                        null=True,
                        verbose_name="요일1",
                    ),
                ),
                (
                    "day_2",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                            (6, "일요일"),
                        ],
                        null=True,
                        verbose_name="요일2",
                    ),
                ),
                (
                    "day_3",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                            (6, "일요일"),
                        ],
                        null=True,
                        verbose_name="요일3",
                    ),
                ),
                (
                    "custom_dates",
                    models.TextField(
                        blank=True,
                        help_text="쉼표로 구분: 2025-06-03,2025-06-10",
                        verbose_name="직접입력 날짜들",
                    ),
                ),
                ("notice", models.TextField(blank=True, verbose_name="수강생 공지")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gx_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="classes.gxclass",
                        verbose_name="수업",
                    ),
                ),
            ],
            options={
                "verbose_name": "수업 일정",
                "verbose_name_plural": "수업 일정 목록",
                "ordering": ["-start_date"],
            },
        ),
    ]
