# Generated by Django 4.2.16 on 2026-06-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateLessonRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("phone", models.CharField(max_length=15, verbose_name="연락처")),
                ("building", models.CharField(max_length=10, verbose_name="동")),
                ("unit", models.CharField(max_length=10, verbose_name="호수")),
                ("preferred_time", models.TextField(verbose_name="희망시간대")),
                ("message", models.TextField(verbose_name="요청내용")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "검토중"),
                            ("confirmed", "확정"),
                            ("rejected", "거절"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="처리상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "개인레슨요청",
                "verbose_name_plural": "개인레슨요청 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("phone", models.CharField(max_length=15, verbose_name="연락처")),
                ("building", models.CharField(max_length=10, verbose_name="동")),
                ("unit", models.CharField(max_length=10, verbose_name="호수")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "예약확정"),
                            ("waiting", "대기중"),
                            ("cancelled", "취소"),
                        ],
                        default="confirmed",
                        max_length=15,
                        verbose_name="예약상태",
                    ),
                ),
                (
                    "waiting_order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="대기순번"
                    ),
                ),
                (
                    "cancel_requested",
                    models.BooleanField(default=False, verbose_name="변경요청"),
                ),
                (
                    "cancel_message",
                    models.TextField(blank=True, verbose_name="변경요청내용"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="예약일시"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gx_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="classes.gxclass",
                        verbose_name="수업",
                    ),
                ),
            ],
            options={
                "verbose_name": "예약",
                "verbose_name_plural": "예약 목록",
                "ordering": ["gx_class", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "출석"),
                            ("absent", "결석"),
                            ("makeup", "보강"),
                        ],
                        default="present",
                        max_length=10,
                        verbose_name="출석상태",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=100, verbose_name="메모"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="bookings.booking",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="classes.classsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "출석",
                "verbose_name_plural": "출석 목록",
                "unique_together": {("session", "booking")},
            },
        ),
    ]
